sudo: true # needed to start docker daemon

services:
  - docker # required, but travis uses older version of docker :(

language: groovy

jdk:
  - oraclejdk8

notifications:
  # email: false
  email:
    # defauls are committer and author if they have repo rights
    recipients:
      - foobar@umich.edu
      - talktothehand@umich.edu
    on_success: never  # default: change
    on_failure: always # default: always
    # see also
    # https://docs.travis-ci.com/user/notifications#Configuring-Slack-notifications

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

install:
  - echo "install nothing!" # put your normal pre-testing installs here

script:
  - ./gradlew assemble # put your normal testing stuff here, return non-zero on failure

deploy:
  skip_cleanup: true
  provider: script
  script: bash travis-buildit
  on:
    branch: master

# using deploy > script b/c we have a bit more stuff going on than after_success will allow...

# after_success:
#   - docker --version  # document the version travis is using
#   - pip install --user awscli # install aws cli w/o sudo
#   - export PATH=$PATH:$HOME/.local/bin # put aws in the path
#   - eval $(aws ecr get-login --region us-east-1) #needs AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY envvars
#   - docker build -t my_example_app .
#   - docker tag my_example_app:latest [your_ecr_account].dkr.ecr.us-east-1.amazonaws.com/my_example_app:latest
#   - docker push [your_ecr_account].dkr.ecr.us-east-1.amazonaws.com/my_example_app:latest
