sudo: true

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

language: groovy

jdk:
  - oraclejdk8

services:
  - docker # required, but travis uses older version of docker :(

install:
  - echo "install nothing!" # put your normal pre-testing installs here

script:
  - gradle assemble

deploy:
  -  provider: script
     script: bash travis-buildit
     on:
       branch: master

# after_success:
#   - docker --version  # document the version travis is using
#   - pip install --user awscli # install aws cli w/o sudo
#   - export PATH=$PATH:$HOME/.local/bin # put aws in the path
#   - eval $(aws ecr get-login --region us-east-1) #needs AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY envvars
#   - docker build -t my_example_app .
#   - docker tag my_example_app:latest [your_ecr_account].dkr.ecr.us-east-1.amazonaws.com/my_example_app:latest
#   - docker push [your_ecr_account].dkr.ecr.us-east-1.amazonaws.com/my_example_app:latest
