#!/bin/bash

EXIT_STATUS=0

echo "deploying..."

REGISTRY=803057437978.dkr.ecr.us-east-1.amazonaws.com

REPOOWNER=knoxilla
REPONAME=travis-test

REPO=${REPOOWNER}/${REPONAME}

GRAILSENV=${1-production}
VERSION=$(gradle -q appVersion)
DOCKERFILE="docker/Dockerfile"

env | sort

echo "selecting python..."
pyenv global 3.6
python --version
python3 --version
pip --version
pip3 --version

echo "awscli..."
echo ${AWS_ACCESS_KEY_ID}
echo ${AWS_SECRET_ACCESS_KEY}

docker --version  # document the version travis is using
pip3 install --user awscli # install aws cli w/o sudo
export PATH=$PATH:$HOME/.local/bin # put aws in the path
echo "Logging in to AWS ECR..."
eval $(aws ecr get-login --region us-east-1 --no-include-email) #needs AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY envvars

echo "copy war..."

cp ./build/libs/${REPONAME}-${VERSION}.war ./application-${VERSION}.war

TAG=${2-$VERSION}

docker build --compress \
    --build-arg GIT_COMMIT=$(git rev-parse --short HEAD) \
    --build-arg GIT_REPOPATH=$(git config --get remote.origin.url | cut -d: -f2- | cut -d. -f1) \
    --build-arg GIT_REPOHOST=$(git config --get remote.origin.url | cut -d@ -f2 | cut -d: -f1) \
    --build-arg appVersion=${VERSION} \
    --build-arg grailsEnv=${GRAILSENV} \
    -t ${REGISTRY}/${REPO}:${TAG} \
    -f ${DOCKERFILE} \
    .

docker push ${REGISTRY}/${REPO}:${TAG}

rm ./application-${VERSION}.war

exit $EXIT_STATUS

